### PR TITLE
Feature/sidebar updates

### PR DESCRIPTION
**Pull request by thespacedoctor**
Please remember to follow the Lasair Pull Request checklist when issuing & reviewing this pull request:

https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2612264961/How+to+do+Pull+Request#STEP-3%3A-Issue-a-Pull-Request-on-Github

# CHANGES

- @RoyWilliams added some links to the sidebar

image

### CODE REVIEW

**Comment by RoyWilliams** [comment]
Please can you add a new link "Get Started" or 'Quickstart". Meg is right, it must be there.

I will write something that explains about filtering and some of the available attributes "my first filter"

**Comment by thespacedoctor** [comment]
Hi @RoyWilliams how about this:





Rich and Tidy!? 

- The documentation links will open a new tab
- The about page is a placeholder link for now (we can add an issue to create a nice about page)
- The annotators have their own icon now
- Schema browser maybe belongs in the bottom section?

**Comment by RoyWilliams** [comment]
Can't they all be visible? Why the strip tease behind the awful word Documentation?? 
Four items not hidden:
- About
- Quickstart Guide
- API and Notebooks
- FAQ

**Comment by RoyWilliams** [comment]
I like the luggage tag!

**Comment by thespacedoctor** [comment]
Let's push it to the team (again!)

**Comment by thespacedoctor** [comment]
Test fails seem to be to do with yesterday's outage. Do you agree @gpfrancis ?

image

**Comment by RoyWilliams** [comment]
If Gareth doesn't take this, I will [give Kafka a kick](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2998108161/Kafka)

**Comment by RoyWilliams** [comment]
I restarted the docker containers
```
ubuntu@lasair-dev-kafka-0:~$ sudo docker ps -a
CONTAINER ID   IMAGE                             COMMAND                  CREATED        STATUS          PORTS     NAMES
8a9b7616a1f9   gpfrancis/lasairmm:2.4.0          "bin/kafka-mirror-ma…"   2 months ago   Up 5 seconds              mirrormaker_mirrormaker_1
b6785d2e2619   confluentinc/cp-kafka:5.4.0       "/etc/confluent/dock…"   2 months ago   Up 18 seconds             ubuntu_kafka_1
07095c5d670c   confluentinc/cp-zookeeper:5.4.0   "/etc/confluent/dock…"   2 months ago   Up 30 seconds             zookeeper_zookeep_1
```

**Comment by thespacedoctor** [comment]
I manually triggered a jenkins build but get the same timeout error :(

The issue is unrelated to this feature, so I think we can merge. Shall I?

**Comment by RoyWilliams** [comment]
I think so, yes. The error from Jenkins is about no response from Kafka, so connected to the Somerville crapfest yesterday, not the web development.

**Pull request merged**
