### PR TITLE
New ingest

### PR DESCRIPTION
**Pull request by RoyWilliams**
New ingestion code and ingest runner. Cleaner code, and gets the alerts even when delayed past midnight. 
 - Tested that SIGTERM stops ingest+runner and ingest cleanly with no processes left over
 - Tested that removing lockfile pauses processing, the runners just sleep until lockfile is back
 - Docopt for arguments to ingest_runner and ingest

### CODE REVIEW

**Comment by gpfrancis** [comment]
Looks OK.

Does this fix the multiple alert ingest issue?

**Comment by RoyWilliams** [comment]
Yes. By default it has the regex to take all alerts. And also arguments to get a specific topic or nid if thats what you want.

**Comment by gpfrancis** [comment]
Sorry, I was asking if this fixes #56 or not.

**Comment by RoyWilliams** [comment]
It *should* fix 56. Certainly we are no longer starting and stopping the kafka consumer every 2 minutes. I want to leave it run over the weekend without touching anything, then hope that the various numbers that should be the same actually are the same.

**Comment by gpfrancis** [comment]
OK. In that case we should probably hold off on merging the PR until Monday.

**Comment by RoyWilliams** [comment]
The counting is accurate

**Pull request merged**
