### PR TITLE
Feature/annotators

### PR DESCRIPTION
**Pull request by thespacedoctor**
Please remember to follow the Lasair Pull Request checklist when issuing & reviewing this pull request:

https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2612264961/How+to+do+Pull+Request#STEP-3%3A-Issue-a-Pull-Request-on-Github

# CHANGES

- Roy's annotator pages

### CODE REVIEW

**Comment by thespacedoctor** [comment]
Hi @RoyWilliams. Like the new annotator integrations ... much more what I originally had in mind.

## QUESTIONS

- [ ] Does the concept of My Annotators and Public Gallery work for annotators? I was under the assumption that annotators didn't really belong to a person but were submitted for review and added by the team.
- [ ] Does the concept of active work with Annotators? 

image

## Change Requests

- [ ] Add schema definition to the Annotator Result table header @thespacedoctor 

    
image

- [ ] format the classdict to read more clearly. How about making the 'classification' in each row a clickable link that reviews a pop-over with the JSON content of classdict?

image

- [ ] give annotators their own icon @thespacedoctor 

image

**Comment by thespacedoctor** [comment]
New icon!

image

**Comment by thespacedoctor** [comment]
Table header schema tooltips working

image

**Comment by thespacedoctor** [comment]
CHANGES:

- Annotator index header formatting fix and text updated

image

- Annotator owner images added

image

- Raw HTML now renders in 'more' popover

image

- updated details header and reformatted the 'classdict' to a code block

image

- My Annotator table only appears if a user owns an annotator, otherwise it is hidden showing only the public gallery.

**Comment by thespacedoctor** [comment]
Are you happy with these updates @RoyWilliams? If so shall we can merge :)

**Comment by RoyWilliams** [comment]
Looks good!

**Pull request merged**
